### ISSUE TITLE
LabPi not empyting chemicals since switch to Google Auth

### ISSUE THREAD

**Issue by michaelplews** [CabanaLab/LabPi#3]
The .log file returns 200 (success) when a container is scanned, however the chemical is not emptied.
professor_oak.log provides no output for this issue.

A number of a real container returns 200, while an incorrect number returns 404.

ISSUE: UIC authentication fails for LabPi user as there is no UIC account for him! 200 returned due to the URL being good, however PATCH fails due to failed AUTH

**Comment by canismarko** [comment]
How does the pi authenticate itself to the server?
